import os
from typing import Optional
from keil_bridge.parser import KeilProject


class CMakeExporter:
    """Exports a Keil project (.uvprojx) target configuration to CMakeLists.txt."""

    def __init__(self, project: KeilProject):
        self.project = project

    def export(self, output_path: Optional[str] = None, target_name: Optional[str] = None) -> str:
        """Generates and writes a CMakeLists.txt file for the target."""
        target = self.project.get_target(target_name)
        
        if not output_path:
            output_path = os.path.join(self.project.project_dir, "CMakeLists.txt")

        # Sanitize project/target name for CMake
        cmake_project_name = target.name.replace(" ", "_").replace("-", "_")

        # Separate source files, header files, libraries
        sources = []
        headers = []
        libraries = []
        unknowns = []

        for group in target.groups:
            for file in group.files:
                # Get relative path with forward slashes
                rel_path = file.relative_path
                
                if file.file_type_code in (1, 2, 3):  # C, C++, Assembly
                    sources.append((group.name, rel_path))
                elif file.file_type_code == 4:  # Header
                    headers.append((group.name, rel_path))
                elif file.file_type_code == 7:  # Library (.lib/.a)
                    libraries.append(rel_path)
                else:
                    unknowns.append((group.name, rel_path))

        # Format preprocessor definitions
        defines_str = ""
        if target.defines:
            defines_str = "\ntarget_compile_definitions(${PROJECT_NAME} PRIVATE\n"
            for d in target.defines:
                defines_str += f"    {d}\n"
            defines_str += ")\n"

        # Format include paths
        includes_str = ""
        if target.include_paths:
            includes_str = "\ntarget_include_directories(${PROJECT_NAME} PRIVATE\n"
            for path in target.include_paths:
                includes_str += f"    {path}\n"
            includes_str += ")\n"

        # Format source list grouped by Keil virtual groups
        sources_list_str = ""
        for group_name, file_path in sources:
            # We add a comment indicating the group name in Keil
            sources_list_str += f"    {file_path} # Group: {group_name}\n"

        # Format library link list
        libraries_str = ""
        if libraries:
            libraries_str = "\ntarget_link_libraries(${PROJECT_NAME} PRIVATE\n"
            for lib in libraries:
                libraries_str += f"    {lib}\n"
            libraries_str += ")\n"

        # Construct final CMake content
        cmake_content = f"""# Generated by uvision-bridge
cmake_minimum_required(VERSION 3.15)

# Uncomment the section below if cross-compiling with arm-none-eabi-gcc
# ====================================================================
# set(CMAKE_SYSTEM_NAME Generic)
# set(CMAKE_SYSTEM_PROCESSOR arm)
# set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
# 
# set(CMAKE_C_COMPILER arm-none-eabi-gcc)
# set(CMAKE_CXX_COMPILER arm-none-eabi-g++)
# set(CMAKE_ASM_COMPILER arm-none-eabi-gcc)
# ====================================================================

project({cmake_project_name} LANGUAGES C CXX ASM)

# Compiler flags and optimizations
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Define executable target
add_executable(${{PROJECT_NAME}}
{sources_list_str})
{includes_str}{defines_str}{libraries_str}
# Embedded compilation properties (adjust flags as needed for target CPU: {target.cpu})
# target_compile_options(${{PROJECT_NAME}} PRIVATE
#     -mcpu=cortex-m3   # example
#     -mthumb
#     -Wall
#     -fdata-sections
#     -ffunction-sections
# )
"""

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(cmake_content)

        return output_path
